-- First, let's check the user's details
SELECT USER_ID, FULL_NAME, ROLE_ID, IS_ACTIVE
FROM USERS 
WHERE USER_ID = 14;

-- Check direct user permissions
SELECT 
    p.PERMISSION_NAME,
    up.ASSIGNED_DATE,
    up.ASSIGNED_BY,
    up.EXPIRATION_DATE
FROM USER_PERMISSIONS up
JOIN PERMISSIONS p ON up.PERMISSION_ID = p.PERMISSION_ID
WHERE up.USER_ID = 14;

-- Check role-based permissions
SELECT 
    r.ROLE_NAME,
    p.PERMISSION_NAME
FROM USERS u
JOIN ROLES r ON u.ROLE_ID = r.ROLE_ID
JOIN ROLE_PERMISSIONS rp ON r.ROLE_ID = rp.ROLE_ID
JOIN PERMISSIONS p ON rp.PERMISSION_ID = p.PERMISSION_ID
WHERE u.USER_ID = 14;

-- Let's also check the structure of our permissions tables
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USER_PERMISSIONS';
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ROLE_PERMISSIONS';
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PERMISSIONS'; 