-- Create USER_SESSIONS table
CREATE TABLE USER_SESSIONS (
    SESSION_ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    LOGIN_TIME DATETIME NOT NULL DEFAULT GETDATE(),
    LOGOUT_TIME DATETIME NULL,
    IP_ADDRESS NVARCHAR(45) NULL,
    USER_AGENT NVARCHAR(255) NULL,
    CONSTRAINT FK_USER_SESSIONS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create indexes for better performance
CREATE INDEX IX_USER_SESSIONS_USER ON USER_SESSIONS(USER_ID);
CREATE INDEX IX_USER_SESSIONS_LOGIN_TIME ON USER_SESSIONS(LOGIN_TIME);
CREATE INDEX IX_USER_SESSIONS_LOGOUT_TIME ON USER_SESSIONS(LOGOUT_TIME); 