-- Create REVIEWS table
CREATE TABLE REVIEWS (
    REVIEW_ID INT IDENTITY(1,1) PRIMARY KEY,
    COURSE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    RATING DECIMAL(3,1) NOT NULL,
    COMMENT NVARCHAR(MAX),
    RATING_DATE DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_REVIEWS_COURSES FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID),
    CONSTRAINT FK_REVIEWS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create index for faster lookups
CREATE INDEX IX_REVIEWS_COURSE ON REVIEWS(COURSE_ID);
CREATE INDEX IX_REVIEWS_USER ON REVIEWS(USER_ID);
CREATE INDEX IX_REVIEWS_DATE ON REVIEWS(RATING_DATE); 