-- Create SYSTEM_METRICS table
CREATE TABLE SYSTEM_METRICS (
    METRIC_ID INT IDENTITY(1,1) PRIMARY KEY,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    CpuUsage DECIMAL(5,2),
    MemoryUsage DECIMAL(5,2),
    DatabaseConnections INT,
    ResponseTime INT
);

-- Create ERROR_METRICS table
CREATE TABLE ERROR_METRICS (
    METRIC_ID INT IDENTITY(1,1) PRIMARY KEY,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    ErrorRate DECIMAL(5,4),
    TotalRequests INT,
    ErrorCount INT
);

-- Create ERROR_LOGS table
CREATE TABLE ERROR_LOGS (
    LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
    Timestamp DATETIME NOT NULL DEFAULT GETDATE(),
    ErrorType NVARCHAR(50) NOT NULL,
    Path NVARCHAR(255),
    Message NVARCHAR(MAX),
    StackTrace NVARCHAR(MAX),
    UserId INT,
    RequestData NVARCHAR(MAX),
    CONSTRAINT FK_ERROR_LOGS_USERS FOREIGN KEY (UserId) REFERENCES USERS(USER_ID)
);

-- Create indexes for better performance
CREATE INDEX IX_SYSTEM_METRICS_TIMESTAMP ON SYSTEM_METRICS(Timestamp);
CREATE INDEX IX_ERROR_METRICS_TIMESTAMP ON ERROR_METRICS(Timestamp);
CREATE INDEX IX_ERROR_LOGS_TIMESTAMP ON ERROR_LOGS(Timestamp);
CREATE INDEX IX_ERROR_LOGS_TYPE ON ERROR_LOGS(ErrorType); 