-- Create NOTIFICATIONS table if it doesn't exist
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NOTIFICATIONS]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[NOTIFICATIONS] (
        [NOTIFICATION_ID] INT IDENTITY(1,1) PRIMARY KEY,
        [USER_ID] INT NOT NULL,
        [TITLE] NVARCHAR(200) NOT NULL,
        [MESSAGE] NVARCHAR(1000) NOT NULL,
        [TYPE] NVARCHAR(50) NOT NULL,
        [IS_READ] BIT NOT NULL DEFAULT(0),
        [CREATED_AT] DATETIME NOT NULL DEFAULT(GETDATE()),
        CONSTRAINT [FK_NOTIFICATIONS_USERS] FOREIGN KEY ([USER_ID]) REFERENCES [USERS]([USER_ID])
    );

    CREATE NONCLUSTERED INDEX [IX_NOTIFICATIONS_USER_ID] ON [dbo].[NOTIFICATIONS]([USER_ID]);
    CREATE NONCLUSTERED INDEX [IX_NOTIFICATIONS_IS_READ] ON [dbo].[NOTIFICATIONS]([IS_READ]);
    CREATE NONCLUSTERED INDEX [IX_NOTIFICATIONS_CREATED_AT] ON [dbo].[NOTIFICATIONS]([CREATED_AT] DESC);

    PRINT 'NOTIFICATIONS table created successfully.';
END
ELSE
BEGIN
    PRINT 'NOTIFICATIONS table already exists.';
END 