-- First disable foreign key constraints
EXEC sp_MSforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT ALL'

-- Delete data from all permission-related tables in the correct order
DELETE FROM PERMISSION_AUDIT_LOG;
DELETE FROM USER_PERMISSIONS;
DELETE FROM ROLE_PERMISSIONS;
DELETE FROM PERMISSION_HIERARCHY;
DELETE FROM PERMISSIONS;
DELETE FROM PERMISSION_CATEGORIES;

-- Reset identity columns if they exist
DBCC CHECKIDENT ('PERMISSION_AUDIT_LOG', RESEED, 0);
DBCC CHECKIDENT ('PERMISSIONS', RESEED, 0);
DBCC CHECKIDENT ('PERMISSION_CATEGORIES', RESEED, 0);

-- Re-enable foreign key constraints
EXEC sp_MSforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL'

GO 