-- First, ensure we have a super admin user (User ID 14 is the super admin)
UPDATE USERS 
SET ROLE_ID = (SELECT ROLE_ID FROM ROLES WHERE ROLE_NAME = 'ADMIN')
WHERE USER_ID = 14;

-- Grant default VIEW permissions to all admins
INSERT INTO USER_PERMISSIONS (USER_ID, PERMISSION_ID, IS_GRANT, ASSIGNED_BY, ASSIGNED_DATE)
SELECT 
    U.USER_ID,
    P.PERMISSION_ID,
    1, -- IS_GRANT
    14, -- ASSIGNED_BY (super admin)
    GETDATE()
FROM USERS U
CROSS JOIN PERMISSIONS P
WHERE U.ROLE_ID = (SELECT ROLE_ID FROM ROLES WHERE ROLE_NAME = 'ADMIN')
    AND P.PERMISSION_NAME IN ('USER.VIEW', 'COURSE.VIEW')
    AND NOT EXISTS (
        SELECT 1 
        FROM USER_PERMISSIONS UP 
        WHERE UP.USER_ID = U.USER_ID 
        AND UP.PERMISSION_ID = P.PERMISSION_ID
    );

-- Grant MANAGE permissions only to super admin (user ID 14)
INSERT INTO USER_PERMISSIONS (USER_ID, PERMISSION_ID, IS_GRANT, ASSIGNED_BY, ASSIGNED_DATE)
SELECT 
    14, -- Super admin user ID
    P.PERMISSION_ID,
    1, -- IS_GRANT
    14, -- ASSIGNED_BY (self)
    GETDATE()
FROM PERMISSIONS P
WHERE P.PERMISSION_NAME IN ('USER.MANAGE', 'COURSE.MANAGE')
    AND NOT EXISTS (
        SELECT 1 
        FROM USER_PERMISSIONS UP 
        WHERE UP.USER_ID = 14 
        AND UP.PERMISSION_ID = P.PERMISSION_ID
    );

-- Log the initial setup
INSERT INTO PERMISSION_AUDIT_LOG (USER_ID, PERMISSION_ID, ACTION, CHANGED_BY, CHANGE_DATE, REASON)
SELECT 
    UP.USER_ID,
    UP.PERMISSION_ID,
    'INITIAL_SETUP',
    14, -- Changed by super admin
    GETDATE(),
    'Initial permission setup - Default admin permissions'
FROM USER_PERMISSIONS UP
WHERE UP.USER_ID IN (SELECT USER_ID FROM USERS WHERE ROLE_ID = (SELECT ROLE_ID FROM ROLES WHERE ROLE_NAME = 'ADMIN')); 