-- First, ensure the USER.MANAGE permission exists
IF NOT EXISTS (SELECT 1 FROM PERMISSIONS WHERE PERMISSION_CODE = 'USER.MANAGE')
BEGIN
    INSERT INTO PERMISSIONS (PERMISSION_CODE, DESCRIPTION, CATEGORY_ID)
    VALUES ('USER.MANAGE', 'Manage user accounts and permissions',
        (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'User Management'));
END

-- Grant the permission to admin users
INSERT INTO USER_PERMISSIONS (USER_ID, PERMISSION_ID, GRANTED_DATE)
SELECT u.USER_ID, p.PERMISSION_ID, GETDATE()
FROM USERS u
CROSS JOIN PERMISSIONS p
WHERE u.ROLE_ID = 1 -- Admin role
AND p.PERMISSION_CODE = 'USER.MANAGE'
AND NOT EXISTS (
    SELECT 1 FROM USER_PERMISSIONS up 
    WHERE up.USER_ID = u.USER_ID 
    AND up.PERMISSION_ID = p.PERMISSION_ID
); 