-- Initialize Permission Categories
INSERT INTO PERMISSION_CATEGORIES (CATEGORY_NAME, DESCRIPTION) VALUES
('Course Management', 'Permissions related to course creation and management'),
('User Management', 'Permissions related to user administration'),
('Content Management', 'Permissions related to educational content'),
('Analytics', 'Permissions related to reporting and analytics'),
('System Administration', 'Permissions related to system configuration');

-- Initialize Basic Permissions
INSERT INTO PERMISSIONS (PERMISSION_CODE, DESCRIPTION, CATEGORY_ID) VALUES
-- Course Management
('COURSE.VIEW', 'View course details', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Course Management')),
('COURSE.CREATE', 'Create new courses', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Course Management')),
('COURSE.EDIT', 'Edit existing courses', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Course Management')),
('COURSE.DELETE', 'Delete courses', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Course Management')),
('COURSE.PUBLISH', 'Publish or unpublish courses', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Course Management')),

-- User Management
('USER.VIEW', 'View user profiles', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'User Management')),
('USER.CREATE', 'Create new users', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'User Management')),
('USER.EDIT', 'Edit user profiles', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'User Management')),
('USER.DELETE', 'Delete users', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'User Management')),
('USER.MANAGE', 'Manage user roles and permissions', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'User Management')),

-- Content Management
('CONTENT.VIEW', 'View educational content', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Content Management')),
('CONTENT.CREATE', 'Create new content', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Content Management')),
('CONTENT.EDIT', 'Edit existing content', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Content Management')),
('CONTENT.DELETE', 'Delete content', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Content Management')),
('CONTENT.PUBLISH', 'Publish or unpublish content', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Content Management')),

-- Analytics
('REPORT.VIEW', 'View analytics reports', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Analytics')),
('REPORT.EXPORT', 'Export analytics data', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Analytics')),
('REPORT.CREATE', 'Create custom reports', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'Analytics')),

-- System Administration
('SYSTEM.CONFIG', 'Manage system configuration', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'System Administration')),
('PERMISSION.MANAGE', 'Manage system permissions', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'System Administration')),
('SYSTEM.BACKUP', 'Manage system backups', (SELECT CATEGORY_ID FROM PERMISSION_CATEGORIES WHERE CATEGORY_NAME = 'System Administration'));

-- Set up permission hierarchy
UPDATE PERMISSIONS 
SET PARENT_PERMISSION_ID = (SELECT PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE = 'COURSE.VIEW')
WHERE PERMISSION_CODE IN ('COURSE.CREATE', 'COURSE.EDIT', 'COURSE.DELETE', 'COURSE.PUBLISH');

UPDATE PERMISSIONS 
SET PARENT_PERMISSION_ID = (SELECT PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE = 'USER.VIEW')
WHERE PERMISSION_CODE IN ('USER.CREATE', 'USER.EDIT', 'USER.DELETE', 'USER.MANAGE');

UPDATE PERMISSIONS 
SET PARENT_PERMISSION_ID = (SELECT PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE = 'CONTENT.VIEW')
WHERE PERMISSION_CODE IN ('CONTENT.CREATE', 'CONTENT.EDIT', 'CONTENT.DELETE', 'CONTENT.PUBLISH');

UPDATE PERMISSIONS 
SET PARENT_PERMISSION_ID = (SELECT PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE = 'REPORT.VIEW')
WHERE PERMISSION_CODE IN ('REPORT.EXPORT', 'REPORT.CREATE');

-- Grant all permissions to admin role (assuming role_id 1 is admin)
INSERT INTO USER_PERMISSIONS (USER_ID, PERMISSION_ID, GRANTED_DATE)
SELECT u.USER_ID, p.PERMISSION_ID, GETDATE()
FROM USERS u
CROSS JOIN PERMISSIONS p
WHERE u.ROLE_ID = 1; 